name: Destroy


on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Which AWS environment do you want to blow up?
        options:
          - staging
          - prod

jobs:
  destroy:
    name: Destroy Terraform
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Terraform Destroy
        env:  
          AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          export TF_WORKSPACE=${{ github.event.inouts.environment }}
          cd terraform/
          docker compose run --rm terraform -chdir=deploy/ init
          docker compose run --rm terraform -chdir=deploy/ destroy -auto-approve
